domain:
  datasource:
    generate-dll: 'false'
    driver-class: com.mysql.jdbc.Driver;
spring:
  jpa:
    hibernate:
      ddl_auto: update
    show_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: Construction Management
  thymeleaf:
    cache: 'false  '
    suffix: '.html '
  datasource:
    password: Manuchaitu7787
    username: root
    url: jdbc:mysql://localhost:3306/constructionManagement
  mvc:
    view:
      prefix: /resources/templates/
      sufix: .html
  messages:
    basename: Validation
server:
  port: '7787'
  error:
    include-message: always
